//Maya ASCII 2025ff03 scene
//Name: dependency-sequence-probe.ma
//Last modified: Tue, Aug 25, 2026 07:11:51 PM
//Codeset: 936
requires maya "2025ff03";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2025";
fileInfo "version" "2025";
fileInfo "cutIdentifier" "202607282326-cffc1a54f2";
fileInfo "osv" "Windows 11 Pro v2009 (Build: 26200)";
fileInfo "UUID" "4F4CA86E-4BF6-3A7F-0C0A-2496CE707401";
createNode transform -s -n "persp";
	rename -uid "4D6FAB5F-440E-8ED1-057C-E1BA05A013F8";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 28 21 28 ;
	setAttr ".r" -type "double3" -27.938352729602379 44.999999999999972 -5.172681101354183e-14 ;
createNode camera -s -n "perspShape" -p "persp";
	rename -uid "1C9AAEA0-493B-5990-7ECF-2A9CBD84FA2F";
	setAttr -k off ".v" no;
	setAttr ".fl" 34.999999999999993;
	setAttr ".coi" 44.82186966202994;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
createNode transform -s -n "top";
	rename -uid "4899892A-47C6-A318-6916-9C8205AF9974";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 1000.1 0 ;
	setAttr ".r" -type "double3" -90 0 0 ;
createNode camera -s -n "topShape" -p "top";
	rename -uid "1019B960-4C0E-5292-DC53-CDBD3E194BC4";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
createNode transform -s -n "front";
	rename -uid "6FB198F4-4D94-FB39-ED41-07BE2E58C5C1";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 1000.1 ;
createNode camera -s -n "frontShape" -p "front";
	rename -uid "F7D656C3-4CDD-1494-E34B-7681BE02BCBF";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
createNode transform -s -n "side";
	rename -uid "71E26839-4FAF-ACBC-09B4-4686348A9999";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 1000.1 0 0 ;
	setAttr ".r" -type "double3" 0 90 0 ;
createNode camera -s -n "sideShape" -p "side";
	rename -uid "E273986E-430B-2722-995C-A2BA859B9CBB";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
createNode lightLinker -s -n "lightLinker1";
	rename -uid "07A85698-4342-00AF-0F8A-038E0EE25C32";
	setAttr -s 2 ".lnk";
	setAttr -s 2 ".slnk";
createNode displayLayerManager -n "layerManager";
	rename -uid "1663B396-45D3-3F7F-C64C-D4850B0BBD6A";
createNode displayLayer -n "defaultLayer";
	rename -uid "579EAB22-43EF-38CF-1104-50B08C27623C";
	setAttr ".ufem" -type "stringArray" 0  ;
createNode renderLayerManager -n "renderLayerManager";
	rename -uid "2783CFB8-4B56-A4BB-8AF9-AF94A3326AA1";
createNode renderLayer -n "defaultRenderLayer";
	rename -uid "73D97552-4B1B-8526-8D8D-028988763CD2";
	setAttr ".g" yes;
createNode file -n "plateSequence";
	rename -uid "CC7DA04D-48B4-23B6-D419-66AFD8C44E82";
	setAttr ".ftn" -type "string" "D:/3D/_tools/MayaScope//examples/assets/mayascope_plate.0001.exr";
	setAttr ".ufe" yes;
	setAttr ".cs" -type "string" "Raw";
createNode file -n "heroUdim";
	rename -uid "7FC8ABA2-4396-55FA-C0E1-CEBBBA19AFA6";
	setAttr ".ftn" -type "string" "examples/assets/mayascope_hero.<UDIM>.exr";
	setAttr ".uvt" 3;
	setAttr ".cs" -type "string" "Raw";
createNode script -n "uiConfigurationScriptNode";
	rename -uid "B0883043-4888-0C60-7FBA-5A80A033549C";
	setAttr ".b" -type "string" "// Maya Mel UI Configuration File.\n// No UI generated in batch mode.\n";
	setAttr ".st" 3;
createNode script -n "sceneConfigurationScriptNode";
	rename -uid "653BCAE3-46B5-587C-60FC-8AA38AF17182";
	setAttr ".b" -type "string" "playbackOptions -min 1 -max 3 -ast 1 -aet 3 ";
	setAttr ".st" 6;
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
	setAttr ".rtfm" 1;
select -ne :renderPartition;
	setAttr -s 2 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 5 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderingList1;
select -ne :defaultTextureList1;
	setAttr -s 2 ".tx";
select -ne :standardSurface1;
	setAttr ".bc" -type "float3" 0.40000001 0.40000001 0.40000001 ;
	setAttr ".sr" 0.5;
select -ne :initialShadingGroup;
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	addAttr -ci true -h true -sn "dss" -ln "defaultSurfaceShader" -dt "string";
	setAttr ".dss" -type "string" "standardSurface1";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".vtn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".vn" -type "string" "ACES 1.0 SDR-video";
	setAttr ".dn" -type "string" "sRGB";
	setAttr ".wsn" -type "string" "ACEScg";
	setAttr ".otn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".potn" -type "string" "ACES 1.0 SDR-video (sRGB)";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr ":defaultColorMgtGlobals.cme" "plateSequence.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "plateSequence.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "plateSequence.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "plateSequence.ws";
connectAttr ":defaultColorMgtGlobals.cme" "heroUdim.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "heroUdim.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "heroUdim.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "heroUdim.ws";
connectAttr "defaultRenderLayer.msg" ":defaultRenderingList1.r" -na;
connectAttr "plateSequence.msg" ":defaultTextureList1.tx" -na;
connectAttr "heroUdim.msg" ":defaultTextureList1.tx" -na;
dataStructure -fmt "raw" -as "name=externalContentTable:string=node:string=key:string=upath:uint32=upathcrc:string=rpath:string=roles";
applyMetadata -fmt "raw" -v "channel\nname externalContentTable\nstream\nname v1.0\nindexType numeric\nstructure externalContentTable\n0\n\"plateSequence\" \"fileTextureName\" \"D:/3D/_tools/MayaScope/examples/assets/mayascope_plate.0001.exr\" 1360146070 \"D:/3D/_tools/MayaScope/examples/assets/mayascope_plate.0001.exr\" \"fileSequence;sourceImages\"\n1\n\"heroUdim\" \"fileTextureName\" \"examples/assets/mayascope_hero.<UDIM>.exr\" 3626528309 \"\" \"sourceImages\"\nendStream\nendChannel\nendAssociations\n" 
		-scn;
// End of dependency-sequence-probe.ma
